language: node_js
node_js:
  - 13.13.0

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test -- --watchAll=false

jobs:
  include:
    - stage: deploy
      script:
        - yarn expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - yarn expo publish --non-interactive
